apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: prom 
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: consul
        image: consul
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8500
          hostPort: 8500
